# Generated by Django 5.2.1 on 2025-05-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolapplicant',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
