# Generated by Django 5.2.1 on 2025-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_portalpost_subcategory_schoolapplicant_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='application_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
