# Generated by Django 5.2.1 on 2025-08-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_portalpost_user_subcategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolapplicant',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
    ]
