# Generated by Django 5.2.1 on 2025-08-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_schoolapplicant_is_submit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=10)),
                ('post_name', models.CharField(max_length=1000)),
                ('exam_center', models.TextField()),
                ('building', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('room_no', models.CharField(max_length=50)),
                ('exam_date_time', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='schoolapplicant',
            name='applicant_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
