# Generated by Django 5.2.1 on 2025-08-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_seatplan_alter_schoolapplicant_applicant_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalpost',
            name='custom_id',
            field=models.CharField(blank=True, help_text='Enter a unique ID for this job (e.g., JOB-001)', max_length=50, null=True, unique=True, verbose_name='Custom Job ID'),
        ),
    ]
