# Generated by Django 5.2.1 on 2025-08-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_portalpost_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalpost',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='custom_id',
            field=models.CharField(blank=True, help_text='Enter a unique ID for this job (e.g., JOB-001)', max_length=50, null=True, unique=True, verbose_name='Custom Job ID'),
        ),
    ]
