# Generated by Django 5.2.1 on 2025-08-13 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_portalpost_custom_id_subcategory_custom_id'),
    ]

    operations = [
        # Ensure roll_number is unique & indexed (safe forward change)
        migrations.AlterField(
            model_name='schoolapplicant',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        # Keep existing SeatPlan.roll field (removed earlier operations causing FK issues)
        migrations.AddIndex(
            model_name='seatplan',
            index=models.Index(fields=['exam_center', 'building', 'floor', 'room_no'], name='portal_seat_exam_ce_576cba_idx'),
        ),
    ]
