# Generated by Django 5.2.5 on 2025-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_seatplan_roll_seatplan_applicant_and_more'),
    ]

    operations = [
        # Safely drop index if it exists (it was added in 0011)
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS portal_seat_exam_ce_576cba_idx;",
            reverse_sql="CREATE INDEX portal_seat_exam_ce_576cba_idx ON portal_seatplan (exam_center, building, floor, room_no);"
        ),
        # Adjust roll_number back to non-unique (model has non-unique)
        migrations.AlterField(
            model_name='schoolapplicant',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
