# Generated by Django 5.2.5 on 2025-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_seatplan_roll_seatplan_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seatplan',
            name='portal_seat_exam_ce_576cba_idx',
        ),
        migrations.RemoveField(
            model_name='seatplan',
            name='applicant',
        ),
        migrations.AddField(
            model_name='seatplan',
            name='roll',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schoolapplicant',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
