# Generated by Django 5.2.5 on 2025-09-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_seatplan_portal_seat_exam_ce_576cba_idx_and_more'),
    ]

    operations = [
        # Remove the old category_id foreign key column
        migrations.RemoveField(
            model_name='portalpost',
            name='category_id',
        ),
        # Add the new category CharField
        migrations.AddField(
            model_name='portalpost',
            name='category',
            field=models.CharField(
                choices=[('admission', 'Admission'), ('job', 'Job')], 
                max_length=50,
                default='admission'
            ),
            preserve_default=False,
        ),
    ]
