# Generated by Django 5.2.5 on 2025-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_seatplan_portal_seat_exam_ce_576cba_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(help_text="Used as internal value (e.g., 'admission')", max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Category Choices',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='portalpost',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
