# Generated by Django 5.2.5 on 2025-09-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_seatplan_portal_seat_exam_ce_576cba_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Transform category_id to category CharField
            """
            ALTER TABLE portal_portalpost 
            ADD COLUMN category VARCHAR(50) DEFAULT 'admission';
            
            UPDATE portal_portalpost 
            SET category = CASE 
                WHEN category_id = 1 THEN 'admission'
                WHEN category_id = 2 THEN 'job'
                ELSE 'admission'
            END;
            
            ALTER TABLE portal_portalpost 
            DROP COLUMN IF EXISTS category_id;
            """,
            # Reverse SQL - In case we need to rollback
            """
            ALTER TABLE portal_portalpost 
            ADD COLUMN category_id INTEGER;
            
            ALTER TABLE portal_portalpost 
            DROP COLUMN IF EXISTS category;
            """,
        ),
    ]
