# Generated by Django 5.2.5 on 2025-09-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_categorychoice_alter_portalpost_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryChoice',
        ),
        migrations.AlterField(
            model_name='portalpost',
            name='category',
            field=models.CharField(choices=[('admission', 'Admission'), ('job', 'Job')], max_length=50),
        ),
    ]
